User.create(username: 'User1', email: 'user1@me.com', password: 'pfJLGmA5')
User.create(username: 'User2', email: 'user2@me.com', password: 'MxgJrxHP')
User.create(username: 'User3', email: 'user3@me.com', password: 'wbNcvQSm')
User.create(username: 'User4', email: 'user4@me.com', password: 'RDJYPEZB')
User.create(username: 'User5', email: 'user5@me.com', password: 'KmPDyD4Z')
